name: Vortrag 25 Jahre Java - Build Slides

on: 
  push:
  
  watch:
    types: [started]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0 LTS
        uses: actions/setup-java@v1
        with:
          java-version: 11.0
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B clean process-resources -DexecutionId=generate-slides --file pom.xml
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages # The branch the action should deploy to.
         FOLDER: target/generated-slides

